---
version: '3.5'

services:

  laravel:
    image: laravel-elasticbeanstalk:latest
    build: ./php
    ports:
      - 80:80
      - 443:443
    environment:
      - CONTAINER_ROLE=app
    working_dir: /var/www/
    volumes:
      - ../../:/var/www/

  postgres:
    image: postgres:12.1-alpine
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./postgres-testing.sh:/docker-entrypoint-initdb.d/postgres-testing.sh
    environment:
      - POSTGRES_DB=laravelelasticbeanstalk
      - POSTGRES_USER=laraveluser
      - POSTGRES_PASSWORD=87acasdw434csd

  redis:
    image: redis:5.0-alpine

networks:
  default:
    driver: bridge
