version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: AWS_RESOURCE_NAME_PREFIX
          tag: 'apache, AWS_RESOURCE_NAME_PREFIX'
